##############################################################################
#
###############################################################################

PORTVERSION =		0.76
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Excel
PORT_DEPENDS =		Archive-Zip

include ../../etc/ports.mk
