##############################################################################
# $HeadURL: svn://cvs1.rambler.ru/Contenido/trunk/ports/all/Jcode/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		2.07
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Jcode

include ../../etc/ports.mk
