##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/Image-Size/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		2.992
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Image


include ../../etc/ports.mk
