##############################################################################
#
###############################################################################

PORTVERSION =		1.11
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Crypt
PORT_DEPENDS =          Test-Manifest

include ../../etc/ports.mk
