##############################################################################
# $HeadURL: svn://cvs1.rambler.ru/Contenido/trunk/ports/all/Params-Validate/GNUmakefile $
# $Id: GNUmakefile 1625 2011-10-26 15:21:17Z ahitrov $
###############################################################################

PORTVERSION =		1.000007
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Module

include ../../etc/ports.mk
