##############################################################################
# $Id: GNUmakefile 1243 2008-06-17 11:05:36Z abavykin $
###############################################################################

PORTVERSION =		0.90
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	IPC
PORT_DEPENDS =		IO-Tty

include ../../etc/ports.mk
