##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/Module-Build/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		0.2801
PERL_MODBUILD =		yes
MASTER_CPAN_SUBDIR =	Module/KWILLIAMS
PORT_DEPENDS =		PathTools


include ../../etc/ports.mk
