##############################################################################
#
###############################################################################

PORTVERSION =		0.35
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	XML
PORT_DEPENDS =		XML-TreePP
PERL_CHECK_MODULE =	XML-TreePP


include ../../etc/ports.mk
