##############################################################################
#
###############################################################################

include ../../etc/perl.mk

PORTVERSION =		0.04
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Linux

include ../../etc/ports.mk
