##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/DateTime/GNUmakefile $
# $Id: GNUmakefile 1243 2008-06-17 11:05:36Z abavykin $
###############################################################################

PORTVERSION =		0.06
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Math

include ../../etc/ports.mk
