##############################################################################
#
###############################################################################

PORTVERSION =		1.03
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Net
PORT_DEPENDS =		Socket6


include ../../etc/ports.mk
