##############################################################################
# $HeadURL: svn+ssh://svn@kaa5/Contenido/trunk/ports/all/Date-Calc/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		1.03
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Net
PORT_DEPENDS =		Socket6


include ../../etc/ports.mk
