##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/Compress-Zlib/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		1.41
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Compress


include ../../etc/ports.mk
