##############################################################################
# $HeadURL: svn://cvs1.rambler.ru/Contenido/trunk/ports/all/MIME-Base64/GNUmakefile $
# $Id: GNUmakefile 982 2007-07-25 12:24:52Z abavykin $
###############################################################################

#include ../../etc/perl.mk

PORTVERSION =		8.00
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Image

#ifeq (${shell perl -e 'print 1 if ${PERL_LEVEL}<500600'},1)
#PORT_DEPENDS =		XSLoader
#endif

include ../../etc/ports.mk
