##############################################################################
# $HeadURL: 
# $Id: GNUmakefile
###############################################################################

PORTVERSION =		0.08
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	HTML


include ../../etc/ports.mk
