##############################################################################
#
###############################################################################

PORTVERSION =		6.04
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	File
PORT_DEPENDS =		HTTP-Date

include ../../etc/ports.mk
