##############################################################################
#
###############################################################################

include ../../etc/perl.mk

PORTVERSION =           1.003009
PERL_MAKEMAKER =        yes
MASTER_CPAN_SUBDIR =   	JSON
PORT_DEPENDS =		JSON-PP

include ../../etc/ports.mk
