##############################################################################
#
###############################################################################

PORTVERSION =		2.57
PERL_MAKEMAKER =	yes
PERL_CHECK_MODULE =	LWP-Parallel
MASTER_CPAN_SUBDIR =	LWP
PORT_DEPENDS =		libwww			\
			URI			\
			HTML-Parser

include ../../etc/ports.mk
