##############################################################################
#
###############################################################################

PORTVERSION =		6.4
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Date
PORT_DEPENDS =		Bit-Vector


include ../../etc/ports.mk
