##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/Date-Calc/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		5.4
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Date
PORT_DEPENDS =		Bit-Vector


include ../../etc/ports.mk
