##############################################################################
#
###############################################################################

#include ../../etc/perl.mk

PORTVERSION =		1.03
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Digest


include ../../etc/ports.mk
