##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/Time-HiRes/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		1.87
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Time

include ../../etc/ports.mk
