##############################################################################
# $HeadURL: 
# $Id:
###############################################################################

PORTVERSION =		1.4
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Convert
PORT_DEPENDS =          Digest-MD5	\
			MIME-Base64	\
			Compress-Zlib

include ../../etc/ports.mk
