##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/P-WebFetcher/GNUmakefile $
# $Id: GNUmakefile 375 2006-08-23 08:47:17Z abavykin $
###############################################################################

PORTVERSION =		1.0
PORT_DEPENDS =		libwww

do-configure:	;
do-build:	;

do-install:
	@cp -Rp ${WRKSRC}/P ${PREFIX}/lib/perl5/site_perl/${PERL_VER}/

include ../../etc/ports.mk
