##############################################################################
#
###############################################################################

PORTVERSION =		1.58
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Crypt
PORT_DEPENDS =		Crypt-Blowfish		\
			Class-Loader		\
			Convert-ASCII-Armour	\
			Crypt-CBC		\
			Sort-Versions		\
			Tie-EncryptedHash	\
			Data-Buffer		\
			Digest-MD2		\
			Math-Pari		\
			Crypt-Primes		\
			Crypt-Random		\
			Digest-SHA1		\
			Digest-MD5
			
			
                                                

include ../../etc/ports.mk
