##############################################################################
#
###############################################################################

PORTVERSION =		0.012
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Test
PORT_DEPENDS =		Try-Tiny

include ../../etc/ports.mk
