##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/libtiff-lzw-compression-kit/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		1.3

do-configure: 	;
do-build: 	;
do-install: 	;


include ../../etc/ports.mk
