##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/DateTime-Locale/GNUmakefile $
# $Id: GNUmakefile 1243 2008-06-17 11:05:36Z abavykin $
###############################################################################

PORTVERSION =		0.4001
PERL_MODBUILD =		yes
MASTER_CPAN_SUBDIR =	DateTime
PORT_DEPENDS =		Params-Validate		\
			List-MoreUtils


include ../../etc/ports.mk
