##############################################################################
#
###############################################################################

PORTVERSION =		6.06
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	LWP
PORT_DEPENDS =		IO-Socket-SSL			\
			Mozilla-CA			\
			Net-HTTP

include ../../etc/ports.mk
