##############################################################################
#
###############################################################################

PORTVERSION =		6.02
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	WWW
PORT_DEPENDS =		URI

include ../../etc/ports.mk
