##############################################################################
# $HeadURL: svn://cvs1.rambler.ru/Contenido/trunk/ports/all/zip/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		1.2.12
MASTER_POST_SITES =	http://heanet.dl.sourceforge.net/sourceforge/${PORTNAME}	\
			http://nchc.dl.sourceforge.net/sourceforge/${PORTNAME}		\
			http://kent.dl.sourceforge.net/sourceforge/${PORTNAME}		\
			http://easynews.dl.sourceforge.net/sourceforge/${PORTNAME}	\
			http://ufpr.dl.sourceforge.net/sourceforge/${PORTNAME}		\
			http://jaist.dl.sourceforge.net/sourceforge/${PORTNAME}		\
			http://umn.dl.sourceforge.net/sourceforge/${PORTNAME}
INSTALL_PRECMD =	@test -d ${PREFIX}/include || mkdir -p ${PREFIX}/include


include ../../etc/ports.mk
