##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/Error/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		0.15
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Error


include ../../etc/ports.mk
