##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/Cache-Cache/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		1.05
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Cache
PORT_DEPENDS =		Error				\
			IPC-ShareLite			\
			Digest-SHA1			\
			Digest-MD5			\
			Storable			\
			PathTools

include ../../etc/ports.mk
