##############################################################################
#
###############################################################################

#include ../../etc/perl.mk

PORTVERSION =		3.71
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	HTML
PORT_DEPENDS =		HTML-Tagset	\
			URI


include ../../etc/ports.mk
