##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/HTML-Parser/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

#include ../../etc/perl.mk

PORTVERSION =		3.54
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	HTML
PORT_DEPENDS =		HTML-Tagset	\
			URI
#			Test-Simple

#ifeq (${shell perl -e 'print 1 if ${PERL_LEVEL}<500600'},1)
#${call die,requires perl 5.6.0 or higher.};
#endif


include ../../etc/ports.mk
