##############################################################################
#
###############################################################################

PORTVERSION =		0.30.01
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	XML
DISTFILE =		${PORTNAME}-0.3001.tar.gz
PORT_DEPENDS =		XML-LibXML					\
			Class-Accessor					\
			DateTime-Format-Mail				\
			DateTime-Format-W3CDTF				\
			UNIVERSAL-require				\


include ../../etc/ports.mk
