##############################################################################
# $HeadURL: svn://cvs1.rambler.ru/Contenido/trunk/ports/all/PathTools/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		1.96.0
PERL_MODBUILD =		yes
MASTER_CPAN_SUBDIR =	Parse
PORT_DEPENDS =		Text-Balanced


include ../../etc/ports.mk
