##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/Carp-Clan/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		5.3
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Carp


include ../../etc/ports.mk
