##############################################################################
#
###############################################################################

PORTVERSION =		0.06
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Module
PORT_DEPENDS =		Module-Runtime			\
			Try-Tiny

include ../../etc/ports.mk
