##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/MIME-tools/GNUmakefile $
# $Id: GNUmakefile 1149 2008-01-16 10:36:32Z phoinix $
###############################################################################

PORTVERSION =		5.425
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	MIME
PERL_CHECK_MODULE =	MIME-Tools
PORT_DEPENDS =		IO-stringy					\
			MailTools					\
			MIME-Base64


include ../../etc/ports.mk
