##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/Devel-StackTrace/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

#include ../../etc/perl.mk

PORTVERSION =		1.13
PERL_MODBUILD =		yes
MASTER_CPAN_SUBDIR =	Devel
PORT_DEPENDS =		Module-Build

#ifeq (${shell perl -e 'print 1 if ${PERL_LEVEL}<500800'},1)
#PORT_DEPENDS =		Test-Simple
#endif

include ../../etc/ports.mk
