##############################################################################
#
###############################################################################

#include ../../etc/perl.mk

PORTVERSION =		2.02
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Devel

include ../../etc/ports.mk
