##############################################################################
#
###############################################################################

#include ../../etc/perl.mk

PORTVERSION =		2.02
PERL_MODBUILD =		yes
MASTER_CPAN_SUBDIR =	Devel
PORT_DEPENDS =		Module-Build

#ifeq (${shell perl -e 'print 1 if ${PERL_LEVEL}<500800'},1)
#PORT_DEPENDS =		Test-Simple
#endif

include ../../etc/ports.mk
