##############################################################################
#
###############################################################################

PORTVERSION =		6.06
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	HTTP
PORT_DEPENDS =		Encode-Locale				\
			HTML-Parser				\
			HTTP-Date				\
			IO-HTML					\
			LWP-MediaTypes				\
			URI

include ../../etc/ports.mk
