##############################################################################
# $HeadURL: svn://cvs1.rambler.ru/Contenido/trunk/ports/all/Unicode-String/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

include ../../etc/perl.mk

PORTVERSION =		1.023
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Authen
PORT_DEPENDS =		File-Spec Digest-MD5 GD


include ../../etc/ports.mk
