##############################################################################
# $HeadURL: svn://cvs1.rambler.ru/Contenido/trunk/ports/all/URI/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

include ../../etc/perl.mk

PORTVERSION =           0.42
PERL_MAKEMAKER =        yes
MASTER_CPAN_SUBDIR =   	../../authors/id/Y/YS/YSAS 
PORT_DEPENDS =		Data-TemporaryBag

include ../../etc/ports.mk

