##############################################################################
# $HeadURL: svn://cvs1.rambler.ru/Contenido/trunk/ports/all/MIME-Base64/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

#include ../../etc/perl.mk

PORTVERSION =		0.241
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	DBD/XBase

#ifeq (${shell perl -e 'print 1 if ${PERL_LEVEL}<500600'},1)
#PORT_DEPENDS =		XSLoader
#endif

include ../../etc/ports.mk
