##############################################################################
# $Id: GNUmakefile 1243 2008-06-17 11:05:36Z abavykin $
###############################################################################

PORTVERSION =		2.57
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Module

include ../../etc/ports.mk
