##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/PathTools/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		3.18
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	File
PORT_DEPENDS =		Scalar-List-Utils
PERL_CHECK_MODULE =	File-Spec


include ../../etc/ports.mk
