##############################################################################
#
###############################################################################

PORTVERSION =		0.721
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	XML
PORT_DEPENDS =		Test-Requires

#CONFIGURE_POSTARGS =	EXPATLIBPATH=${PREFIX}/lib 	\
#			EXPATINCPATH=${PREFIX}/include

include ../../etc/ports.mk
