##############################################################################
# $HeadURL: 
# $Id:
###############################################################################

PORTVERSION =		2.28
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Crypt
PORT_DEPENDS =		Digest-MD5

include ../../etc/ports.mk
