##############################################################################
# $HeadURL: svn://cvs1.rambler.ru/Contenido/trunk/ports/all/Date-Calc/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		1.06
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Data
PORT_DEPENDS =		Array-RefElem


include ../../etc/ports.mk
