##############################################################################
#
###############################################################################

include ../../etc/perl.mk

PORTVERSION =		1.02
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Class

include ../../etc/ports.mk
