##############################################################################
#
###############################################################################

include ../../etc/perl.mk

PORTVERSION =		2.16
#DISTFILE =		NTLM-${PORTVERSION}.tar.gz
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Authen

include ../../etc/ports.mk
