##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/DateTime/GNUmakefile $
# $Id: GNUmakefile 1243 2008-06-17 11:05:36Z abavykin $
###############################################################################

PORTVERSION =		1.03
PERL_MODBUILD =		yes
MASTER_CPAN_SUBDIR =	DateTime
PORT_DEPENDS =		DateTime-TimeZone				\
			DateTime-Locale					\
			Math-Round					\
			Params-Validate					\
			Test-Fatal

#CONFIGURE_PRECMD =	${MAKE_RECURSIVE} pre-configure
#pre-configure:
#	cd ${WRKSRC}/lib && patch -p0 < ${PORTDIR}/patch.datetime.formatter

include ../../etc/ports.mk
