##############################################################################
# $HeadURL: svn://cvs1.rambler.ru/Contenido/trunk/ports/all/HTML-Parser/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

#include ../../etc/perl.mk

PORTVERSION =			0.23
PERL_MAKEMAKER =		yes
MASTER_CPAN_SUBDIR =	Text

include ../../etc/ports.mk
