##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/Unicode-Map8/GNUmakefile $
# $Id: GNUmakefile 1526 2010-03-29 11:11:10Z ahitrov $
###############################################################################

PORTVERSION =		0.12
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Unicode
PORT_DEPENDS =		Unicode-String  \
                    Unicode-Map


include ../../etc/ports.mk
