##############################################################################
#
###############################################################################

PORTVERSION =		1.25
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Crypt
PORT_DEPENDS = 		Class-Loader	\
			Math-Pari

include ../../etc/ports.mk
