##############################################################################
#
###############################################################################

PORTVERSION =		0.018
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Crypt
PORT_DEPENDS =		CryptX			\
			JSON-MaybeXS

include ../../etc/ports.mk
