#!/usr/bin/perl

use strict;

print STDERR <<EOM;
-----------------------------------------------
Создание пользователей редакторского интерфейса
-----------------------------------------------
Эта программа умеет создавать пользователей для доступа к редакторскому интерфейсу.
Для того, чтобы закончить работу программы - введите пустое имя пользователя.

EOM

my @users;

my $count = 0;
while (1) {
	print STDERR "Пользователь: ";
	my $user = <STDIN>;
	chomp($user);
	last unless (length($user));

	print STDERR "Пароль пользователя '$user': ";
	my $password = <STDIN>;
	chomp($password);

	print STDERR "Введите ФИО пользователя '$user': ";
	my $fio = <STDIN>;
	chomp($fio);

	push @users, [$user, $password, $fio];

	print STDERR "Пользователь '$user' с паролем '$password' создан.\n\n";
	$count++;
};
print STDERR "Создано пользователей: $count\n\n";

print "INSERT INTO USERS (login, class, status, name, passwd, groups) VALUES ('$_->[0]', 'Contenido::User', 1, '$_->[2]', '$_->[1]', '{1}');\n" for @users;
