##############################################################################
# $HeadURL: svn://cvs1.rambler.ru/Contenido/trunk/ports/all/Time-Local/GNUmakefile $
# $Id: GNUmakefile 821 2007-04-23 15:04:53Z res $
###############################################################################

PORTVERSION =		2.26
PERL_MAKEMAKER =	yes
PORT_DEPENDS =		common-sense
MASTER_CPAN_SUBDIR =	../../authors/id/M/ML/MLEHMANN


include ../../etc/ports.mk
