##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/String-CRC32/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		1.4
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	String


include ../../etc/ports.mk
