##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/DProf/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

#include ../../etc/perl.mk

PORTVERSION =		19990108
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Devel
PERL_CHECK_MODULE =	Devel-DProf

#ifeq (${shell perl -e 'print 1 if ${PERL_LEVEL}>=500600'},1)
#${call die,Version included in perl distribution is newer.};
#endif


include ../../etc/ports.mk
