##############################################################################
# $Id: GNUmakefile 1243 2008-06-17 11:05:36Z abavykin $
###############################################################################

PORTVERSION =		0.21
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Locale

include ../../etc/ports.mk
