##############################################################################
# $HeadURL: http://developers.rambler.ru/svn/contenido/koi8/core/ports/all/URI/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

include ../../etc/perl.mk

PORTVERSION =		0.14
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Log

include ../../etc/ports.mk
