##############################################################################
# $HeadURL: svn://cvs1.rambler.ru/Contenido/trunk/ports/all/MP3-Info/GNUmakefile $
###############################################################################

PORTVERSION =		1.22
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	MP3


include ../../etc/ports.mk
