##############################################################################
# $HeadURL: svn://cvs1.rambler.ru/Contenido/trunk/ports/all/XML-Parser/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		1.1
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Lingua

#CONFIGURE_POSTARGS =	EXPATLIBPATH=${PREFIX}/lib 	\
#			EXPATINCPATH=${PREFIX}/include

include ../../etc/ports.mk
