##############################################################################
#
###############################################################################

PORTVERSION =		0.09
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	List
PORT_DEPENDS =		List-MoreUtils

include ../../etc/ports.mk
