##############################################################################
# $HeadURL: svn://cvs1.rambler.ru/Contenido/trunk/ports/all/Unicode-Map/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		0.112 
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Unicode


include ../../etc/ports.mk
