##############################################################################
#
###############################################################################

PORTVERSION =		6.02
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	LWP
PORT_DEPENDS =		IO-Compress

include ../../etc/ports.mk
