##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/DateTime-Format-Builder/GNUmakefile $
# $Id: GNUmakefile 285 2006-08-01 12:28:21Z lonerr $
###############################################################################

PORTVERSION =		0.7807
PERL_MODBUILD =		yes
MASTER_CPAN_SUBDIR =	DateTime
PORT_DEPENDS =		Params-Validate					\
			File-Spec					\
			Class-Factory-Util				\
			DateTime					\
			DateTime-Format-Strptime


include ../../etc/ports.mk
