##############################################################################
#
###############################################################################

include ../../etc/perl.mk

PORTVERSION =		0.05
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Apache
PORT_DEPENDS =		Apache-Session		\
			Cache-Memcached


include ../../etc/ports.mk
