##############################################################################
#
###############################################################################

PORTVERSION =		1.42
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Exception
PORT_DEPENDS =		Devel-StackTrace 	\
			Class-Data-Inheritable

include ../../etc/ports.mk
