##############################################################################
# $HeadURL: svn://cvs1.rambler.ru/Contenido/trunk/ports/all/zip/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		1.00
DISTFILE =		${PORTNAME}-${PORTVERSION}.tar.gz
WRKSRC =		${WRKDIR}/${PORTNAME}-${PORTVERSION}
BUILD_ARGS =		prefix=${PREFIX}
INSTALL_ARGS =		install prefix=${PREFIX} 

do-configure: ;

include ../../etc/ports.mk
