##############################################################################
# $Id: GNUmakefile 1243 2008-06-17 11:05:36Z abavykin $
###############################################################################

PORTVERSION =		0.98
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Test
PORT_DEPENDS =		Test-Harness			\
			ExtUtils-MakeMaker

include ../../etc/ports.mk
