##############################################################################
# $HeadURL: svn://cvs1.rambler.ru/Contenido/trunk/ports/all/XML-Hasher/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		2.0001
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	XML/PHISH
PORT_DEPENDS =		XML-LibXML-Common
PORT_DEPENDS +=		XML-SAX
CONFIGURE_POSTARGS =	XMLPREFIX=${PREFIX}


include ../../etc/ports.mk
