##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/libxml-perl/GNUmakefile $
# $Id: GNUmakefile 200 2006-06-22 17:38:47Z lonerr $
###############################################################################

PORTVERSION =		0.08
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	XML
PORT_DEPENDS =		XML-Parser


include ../../etc/ports.mk
