##############################################################################
# $HeadURL: svn://cvs1.rambler.ru/Contenido/trunk/ports/all/DateTime/GNUmakefile $
# $Id: GNUmakefile 821 2007-04-23 15:04:53Z res $
###############################################################################

PORTVERSION =		1.22
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	SQL
DISTFILE ?=		${PORTNAME}${PORTVERSION:%=-%}.tgz
WRKSRC ?=		${WRKDIR}/${DISTFILE:%.tgz=%}


include ../../etc/ports.mk
