##############################################################################
# $HeadURL: svn://cvs1.rambler.ru/Contenido/trunk/ports/all/MIME-Base64/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

include ../../etc/perl.mk

PORTVERSION		= 0.41
DISTFILE		= ${PORTNAME}-${PORTVERSION}.tgz
WRKSRC			= ${WRKDIR}/${DISTFILE:%.tgz=%}
PERL_MAKEMAKER  = yes
CONFIGURE_ENV 	= PERL_MM_USE_DEFAULT=yes
MASTER_CPAN_SUBDIR = Spreadsheet

include ../../etc/ports.mk
