##############################################################################
#
###############################################################################

PORTVERSION =		6.06
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Net
PORT_DEPENDS =		IO-Socket-SSL

include ../../etc/ports.mk
