##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/Class-Factory/GNUmakefile $
# $Id: GNUmakefile 285 2006-08-01 12:28:21Z lonerr $
###############################################################################

PORTVERSION =		1.03
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Class


include ../../etc/ports.mk
