##############################################################################
#
###############################################################################

PORTVERSION =		2.44
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	XML
PORT_DEPENDS =		expat

CONFIGURE_POSTARGS =	EXPATLIBPATH=${PREFIX}/lib 	\
			EXPATINCPATH=${PREFIX}/include

include ../../etc/ports.mk
