##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/XML-Parser/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		2.34
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	XML
PORT_DEPENDS =		expat

CONFIGURE_POSTARGS =	EXPATLIBPATH=${PREFIX}/lib 	\
			EXPATINCPATH=${PREFIX}/include

include ../../etc/ports.mk
