##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/DB_File/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		1.814
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	DB_File


include ../../etc/ports.mk
