##############################################################################
# $HeadURL: svn://cvs1.rambler.ru/Contenido/trunk/ports/all/Exception-Class/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

#include ../../etc/perl.mk

PORTVERSION =		0.52
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Astro

include ../../etc/ports.mk
