##############################################################################
# $HeadURL: svn+ssh://svn@kaa5/Contenido/trunk/ports/all/XML-Parser/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		2.18
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	XML
PORT_DEPENDS =		XML-SAX

CONFIGURE_POSTARGS =	EXPATLIBPATH=${PREFIX}/lib 	\
			EXPATINCPATH=${PREFIX}/include

include ../../etc/ports.mk
