##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/rsync/GNUmakefile $
# $Id: GNUmakefile 287 2006-08-01 14:36:35Z lonerr $
###############################################################################

PORTVERSION =		2.6.8
CONFIGURE_ARGS =	--prefix=${PREFIX}
MASTER_POST_SITES =	ftp://ftp.samba.org/pub/rsync				\
			http://rsync.samba.org/ftp/rsync


include ../../etc/ports.mk
