##############################################################################
#
###############################################################################

include ../../etc/perl.mk

PORTVERSION =		1.39
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Apache


include ../../etc/ports.mk
