##############################################################################
#
###############################################################################

PORTVERSION =		2.066
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	IO
PORT_DEPENDS =		Compress-Raw-Bzip2		\
			Compress-Raw-Zlib

include ../../etc/ports.mk
