##############################################################################
#
###############################################################################

PORTVERSION =		1.21
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Tie
PORT_DEPENDS =		Crypt-CBC	\
			Crypt-Blowfish	\
			Crypt-DES

include ../../etc/ports.mk
