##############################################################################
#
###############################################################################

PORTVERSION =		0.179
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Email
PORT_DEPENDS =		MailTools


include ../../etc/ports.mk
