##############################################################################
#
###############################################################################

include ../../etc/perl.mk

PORTVERSION =		1.09
DISTFILE =		NTLM-${PORTVERSION}.tar.gz
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	../../authors/id/N/NB/NBEBOUT
PORT_DEPENDS =		Digest-HMAC

include ../../etc/ports.mk
