##############################################################################
# $HeadURL: svn://cvs1.rambler.ru/Contenido/trunk/ports/all/URI/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

include ../../etc/perl.mk

PORTVERSION =           1.03
PERL_MAKEMAKER =        yes
MASTER_CPAN_SUBDIR =   	../../authors/id/R/RO/ROODE 

include ../../etc/ports.mk
