##############################################################################
# $HeadURL: svn://cvs1.rambler.ru/Contenido/trunk/ports/all/Storable/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		3.26
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	String

include ../../etc/ports.mk
