##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/Digest-SHA1/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

#include ../../etc/perl.mk

PORTVERSION =		2.11
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Digest

#ifeq (${shell perl -e 'print 1 if ${PERL_LEVEL}<500800'},1)
#PORT_DEPENDS =		Digest
#endif


include ../../etc/ports.mk
