##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/expat/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		1.95.6
INSTALL_POSTCMD =	rm -f ${PREFIX}/lib/libexpat.so*


include ../../etc/ports.mk
