##############################################################################
# $HeadURL: svn://cvs1.rambler.ru/Contenido/trunk/ports/all/URI/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

include ../../etc/perl.mk

PORTVERSION =		0.715
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	SOAP
PORT_DEPENDS =          MIME-Lite					\
			MIME-tools					\
			Crypt-SSLeay					\
			XML-Parser					\
			Task-Weaken					\
			Class-Inspector


include ../../etc/ports.mk
