###############################################################################
#
###############################################################################

include ../../etc/perl.mk

PORTVERSION =		0.716
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	SOAP
PORT_DEPENDS =          MIME-Lite					\
			MIME-tools					\
			Crypt-SSLeay					\
			XML-Parser					\
			XML-Parser-Lite					\
			Task-Weaken					\
			Class-Inspector


include ../../etc/ports.mk
