##############################################################################
# $HeadURL: svn://cvs1.rambler.ru/Contenido/trunk/ports/all/HTML-Parser/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

#include ../../etc/perl.mk

PORTVERSION =		3.23
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	HTML
PORT_DEPENDS =		HTML-Tagset	\
					HTML-Parser

include ../../etc/ports.mk
