##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/BSD-Resource/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		1.28
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	BSD


include ../../etc/ports.mk
