##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/XML-Encoding/GNUmakefile $
# $Id: GNUmakefile 1465 2009-10-27 12:44:36Z ahitrov $
###############################################################################

PORTVERSION =		2.07
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	XML
PORT_DEPENDS =		XML-Parser


include ../../etc/ports.mk
