##############################################################################
# $HeadURL: svn+ssh://svn@vcs.dev.rambler.ru/Contenido/branches/utf8/ports/all/XML-Encoding/GNUmakefile $
# $Id: GNUmakefile 1653 2012-04-08 12:27:35Z ahitrov $
###############################################################################

PORTVERSION =		2.08
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	XML
PORT_DEPENDS =		XML-Parser


include ../../etc/ports.mk
