##############################################################################
# $HeadURL: svn://cvs1.rambler.ru/Contenido/trunk/ports/all/Unicode-MapUTF8/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		1.11
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Unicode
PORT_DEPENDS =		Unicode-String  \
                    Unicode-Map     \
                    Jcode


include ../../etc/ports.mk
