##############################################################################
# $HeadURL: svn://cvs1.rambler.ru/Contenido/trunk/ports/all/zip/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		5.51
DISTFILE =		${PORTNAME}551.tar.gz
WRKSRC =                ${WRKDIR}/${PORTNAME}-${PORTVERSION}
BUILD_ARGS =            -f unix/Makefile prefix=${PREFIX} generic
INSTALL_ARGS =          -f unix/Makefile prefix=${PREFIX} install 

do-configure: ;

include ../../etc/ports.mk
