##############################################################################
#
###############################################################################

PORTVERSION =		6.01
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	HTTP
PORT_DEPENDS =		HTTP-Date				\
			HTTP-Message

include ../../etc/ports.mk
