##############################################################################
# $HeadURL: svn://cvs1.rambler.ru/Contenido/trunk/ports/all/MIME-Base64/GNUmakefile $
# $Id: GNUmakefile 980 2007-07-24 08:49:33Z makc $
###############################################################################

#include ../../etc/perl.mk

PORTVERSION =		0.59
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Imager

#ifeq (${shell perl -e 'print 1 if ${PERL_LEVEL}<500600'},1)
#PORT_DEPENDS =		XSLoader
#endif

include ../../etc/ports.mk
