##############################################################################
#
###############################################################################

PORTVERSION =		0.25
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	../../authors/id/U/UM/UMEMOTO
PORT_DEPENDS =		ExtUtils-MakeMaker


include ../../etc/ports.mk
