##############################################################################
# $HeadURL: svn://cvs1.rambler.ru/Contenido/trunk/ports/all/Time-Local/GNUmakefile $
# $Id: GNUmakefile 821 2007-04-23 15:04:53Z res $
###############################################################################

PORTVERSION =		0.25
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	../../authors/id/U/UM/UMEMOTO
PORT_DEPENDS =		ExtUtils-MakeMaker


include ../../etc/ports.mk
