##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/zip/GNUmakefile $
# $Id: GNUmakefile 1194 2008-03-17 17:27:21Z lonerr $
###############################################################################

PORTVERSION =		2.3
DISTFILE =		${PORTNAME}23.tar.gz
WRKSRC =		${WRKDIR}/${PORTNAME}-${PORTVERSION}
BUILD_ARGS =		MAKEFLAGS= -f unix/Makefile prefix=${PREFIX} generic	
INSTALL_ARGS =		-f unix/Makefile prefix=${PREFIX} install	

do-configure: ;


include ../../etc/ports.mk
