##############################################################################
#
###############################################################################

PORTVERSION =		0.04
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	DateTime
PORT_DEPENDS =		DateTime					\


include ../../etc/ports.mk
