##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/IO-stringy/GNUmakefile $
# $Id: GNUmakefile 172 2006-06-16 12:44:37Z lonerr $
###############################################################################

PORTVERSION =		2.110
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	IO
PERL_CHECK_MODULE =	IO-Stringy


include ../../etc/ports.mk
