##############################################################################
# $HeadURL: svn://cvs1.rambler.ru/Contenido/trunk/ports/all/PathTools/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		v2.0.0
PERL_MODBUILD =		yes
MASTER_CPAN_SUBDIR =	Text


include ../../etc/ports.mk
