##############################################################################
#
###############################################################################

PORTVERSION         =	0.06
PERL_MAKEMAKER      =	yes
MASTER_CPAN_SUBDIR  =	XML
MASTER_CPAN_SUBDIR  =   ../../authors/id/B/BJ/BJOERN
PORT_DEPENDS        =   Class-ArrayObjects

include ../../etc/ports.mk
