##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/File-Temp/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		0.16
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	File
PORT_DEPENDS =		PathTools
#			Test-Simple


include ../../etc/ports.mk
