##############################################################################
# $HeadURL: svn://cvs1.rambler.ru/Contenido/trunk/ports/all/DateTime-Format-Mail/GNUmakefile $
# $Id: GNUmakefile 285 2006-08-01 12:28:21Z lonerr $
###############################################################################

PORTVERSION =		0.04
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	DateTime
PORT_DEPENDS =		DateTime					\
			DateTime-Format-Builder


include ../../etc/ports.mk
