##############################################################################
# $Id: GNUmakefile 1243 2008-06-17 11:05:36Z abavykin $
###############################################################################

PORTVERSION =		1.54
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	ExtUtils

include ../../etc/ports.mk
