##############################################################################
# $HeadURL: svn://cvs1.rambler.ru/Contenido/trunk/ports/all/MIME-Base64/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

include ../../etc/perl.mk


PORTVERSION =		0.86
MASTER_CPAN_SUBDIR =	GD
DISTFILE =		GDTextUtil-${PORTVERSION}.tar.gz
PERL_MAKEMAKER =	yes
PERL_CHECK_MODULE =	GD-Text
PORT_DEPENDS =		GD


include ../../etc/ports.mk
