##############################################################################
# $HeadURL: 
# $Id:
###############################################################################

PORTVERSION =		0.50
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Crypt
PORT_DEPENDS =          Math-Pari	\
			Crypt-Random

include ../../etc/ports.mk