##############################################################################
#
###############################################################################

PORTVERSION =		1.41
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Scalar
PERL_CHECK_MODULE =	Scalar-Util


include ../../etc/ports.mk
