##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/Scalar-List-Utils/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		1.18
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Scalar
PERL_CHECK_MODULE =	Scalar-Util


include ../../etc/ports.mk
