##############################################################################
# $HeadURL: svn://cvs1.rambler.ru/Contenido/trunk/ports/all/DateTime-Locale/GNUmakefile $
# $Id: GNUmakefile 285 2006-08-01 12:28:21Z lonerr $
###############################################################################

PORTVERSION =		0.33
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	List

include ../../etc/ports.mk
