##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/DateTime-Format-Strptime/GNUmakefile $
# $Id: GNUmakefile 285 2006-08-01 12:28:21Z lonerr $
###############################################################################

PORTVERSION =		1.0700
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	DateTime
PORT_DEPENDS =		Params-Validate					\
			DateTime-TimeZone				\
			DateTime


include ../../etc/ports.mk
