##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/XML-Parser-EasyTree/GNUmakefile $
# $Id: GNUmakefile 182 2006-06-19 11:07:54Z abavykin $
###############################################################################

PORTVERSION =		0.01
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	XML
PORT_DEPENDS =		XML-Parser

include ../../etc/ports.mk
