##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/Time-modules/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		2003.1126
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Time
PERL_CHECK_MODULE =	Time-ParseDate


include ../../etc/ports.mk
