##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/Bit-Vector/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		6.4
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Bit
PORT_DEPENDS =		Carp-Clan


include ../../etc/ports.mk
