##############################################################################
#
###############################################################################

PORTVERSION =		7.4
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Bit
PORT_DEPENDS =		Carp-Clan


include ../../etc/ports.mk
