##############################################################################
# $HeadURL: svn://cvs1.rambler.ru/Contenido/trunk/ports/all/zip/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		2.4
DISTFILE =		${PORTNAME}-${PORTVERSION}.tar.gz
WRKSRC =		${WRKDIR}/${PORTNAME}-${PORTVERSION}
BUILD_ARGS =		prefix=${PREFIX}

do-configure: ;
do-install:
	@cp ${WRKDIR}/${PORTNAME}-${PORTVERSION}/jhead ${PREFIX}/bin/


include ../../etc/ports.mk
