##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/MIME-Base64/GNUmakefile $
# $Id: GNUmakefile 982 2007-07-25 12:24:52Z abavykin $
###############################################################################

#include ../../etc/perl.mk

PORTVERSION =		3.13
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	MIME

#ifeq (${shell perl -e 'print 1 if ${PERL_LEVEL}<500600'},1)
#PORT_DEPENDS =		XSLoader
#endif

include ../../etc/ports.mk
