##############################################################################
#
###############################################################################

PORTVERSION =		0.12
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Class
PORT_DEPENDS =		Data-OptList					\
			Package-Stash					\
			Module-Runtime					\
			Try-Tiny

include ../../etc/ports.mk
