##############################################################################
# $HeadURL: 
# $Id: GNUmakefile
###############################################################################

PORTVERSION =		0.33
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	XML

include ../../etc/ports.mk
