##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/Digest-MD5/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		2.36
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Digest
#PORT_DEPENDS =		Digest

include ../../etc/ports.mk
