##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/DateTime-Format-Pg/GNUmakefile $
# $Id: GNUmakefile 285 2006-08-01 12:28:21Z lonerr $
###############################################################################

PORTVERSION =		0.13
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	DateTime
PORT_DEPENDS =		DateTime					\
			DateTime-TimeZone				\
			DateTime-Format-Builder


include ../../etc/ports.mk
