##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/MLDBM/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		2.01
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	MLDBM

#TODO PORT_DEPENDS


include ../../etc/ports.mk
