##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/cyrillic/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		1.05	
PERL_MAKEMAKER =	yes
PORT_DEPENDS =		Unicode-Map8


include ../../etc/ports.mk

