##############################################################################
# $HeadURL: svn://cvs1.rambler.ru/Contenido/trunk/ports/all/zip/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		1.6.2
CONFIGURE_ARGS =	--prefix=${PREFIX} --sbindir=${PREFIX}/bin
MASTER_POST_SITES =	http://cronolog.org/download


include ../../etc/ports.mk
