##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/HTML-Tagset/GNUmakefile $
# $Id: GNUmakefile 175 2006-06-16 12:50:03Z lonerr $
###############################################################################

PORTVERSION =		3.10
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	HTML


include ../../etc/ports.mk
