##############################################################################
# $HeadURL: http://svn.dev.rambler.ru/Contenido/branches/utf8/ports/all/Time-Local/GNUmakefile $
# $Id: GNUmakefile 821 2007-04-23 15:04:53Z res $
###############################################################################

PORTVERSION =		1.17
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Time


include ../../etc/ports.mk
