##############################################################################
#
###############################################################################

PORTVERSION =		0.107
PERL_MAKEMAKER =	yes
MASTER_CPAN_SUBDIR =	Data
PORT_DEPENDS =		Params-Util					\
			Sub-Install

include ../../etc/ports.mk
